pipeline {
	agent any
	tools {
		maven 'Maven3'
	}
	stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}
		stage('Build') {
			steps {
				dir ('starter'){
					sh 'docker build -t team-skeleton:${BUILD_NUMBER} .'
				}
			}
		}
		stage('Test') {
			steps {
				dir ('starter'){
					sh 'mvn -B test'
				}
			}
			post {
				always {
					junit 'starter/target/surefire-reports/*.xml'
				}
			}
		}
	}
}